version: "3.4"
services:
  zookeeper:
    image: "zookeeper:3.6.2"
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: "wurstmeister/kafka:2.13-2.7.0"
    container_name: kafka
    ports:
      - 9093:9093
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: LOCALDOCKER://:9092,LOCAL://:9093
      KAFKA_ADVERTISED_LISTENERS: LOCALDOCKER://kafka:9092,LOCAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LOCALDOCKER:PLAINTEXT,LOCAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LOCALDOCKER

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: 'yes'